name: 'Preview'
description: 'A GitHub Action to deploy an site in preview mode in an test environment'
author: 'GitHub'
on:
  issue_comment:                                     
    actions:
      - created
      - edited
      - deleted
    if: 
      - ${{ github.event.issue.pull_request }}
runs:
  using: 'node16'
inputs:
  token:
    description: 'GitHub token'
    default: ${{ github.token }}
    required: true
  timeout:
    description: 'Time in milliseconds after which to timeout and cancel the deployment (default: 10 minutes)'
    required: false
    default: '600000'
  error_count:
    description: 'Maximum number of status report errors before cancelling a deployment (default: 10)'
    required: false
    default: '10'
  reporting_interval:
    description: 'Time in milliseconds between two deployment status report (default: 5 seconds)'
    required: false
    default: '5000'
  artifact_name:
    description: 'Name of the artifact to deploy'
    required: false
    default: 'github-pages'
outputs:
  page_url:
    description: 'https://staging.laisfrigerio.com.br'
