name: 'Deploy to Vercel - Staging/Test environment'
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  issue_comment:
    types: [created, edited]

jobs:
  deploy:
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'cicd/staging')
    runs-on: ubuntu-latest
    steps:
      - name: Set current branch name
        id: 'get-branch'
        run: | 
          echo "Current branch name.... ${GITHUB_BASE_REF}"
          echo ${GITHUB_BASE_REF}
          echo "branch=${GITHUB_BASE_REF}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
      
      - name: Install Vercel CLI
        run: yarn global add vercel@latest
      
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
